### ISSUE TITLE
noti-center.lua:340 nil value error

### ISSUE THREAD

**Issue by Bad3r** [Mofiqul/awesome-config#1]
Hi,
Thanks for sharing your config. Your post made want to give Awesome WM a try. I am trying to replicate your setup and ran into an error that I can't figure out how to solve
![image](https://user-images.githubusercontent.com/25513724/114404797-0954dc00-9b74-11eb-9a73-9fe046618bf0.png)
the related code block
```lua
naughty.connect_signal("added", function(n)

	if notifbox_layout.children == 1 and remove_notifbox_empty then
		notifbox_layout:reset(notifbox_layout)
		remove_notifbox_empty = false
	end

	local notifbox_color = beautiful.bg_normal
	if n.urgency == 'critical' then
		notifbox_color = beautiful.bg_urgent
	end

	notifbox_layout:insert(1,create_notifbox(n))
end)
```
`rc.lua`:229 is just a call to `noti-center.lua`
```lua
			require("widgets.noti-center"),
```
in your original code there is an extra `#` character in `if #notifbox_layout.children` and I am not sure why. I am new to lua. I tried with and without and both produced the same error
```lua
naughty.connect_signal("added", function(n)

	if #notifbox_layout.children == 1 and remove_notifbox_empty then
		notifbox_layout:reset(notifbox_layout)
		remove_notifbox_empty = false
	end

	local notifbox_color = beautiful.bg_normal
	if n.urgency == 'critical' then
		notifbox_color = beautiful.bg_urgent
	end

	notifbox_layout:insert(1,create_notifbox(n))
end)
```
If you have any idea what could be the cause of this error I would appreciate any help

**Comment by Mofiqul** [comment]
It's look like you have not require naughty 
`local naughty = require('naighty')`
add this on top of `noti-center.lua`

**Comment by GustavoPrietoP** [comment]
![Screenshot from 2021-04-18 18-06-32](https://user-images.githubusercontent.com/70907734/115162320-d6797f00-a070-11eb-87f8-ec4305677bf3.png)
im getting this error now. I have ```local naughty = require('naighty')``` on top of my noti-center.lua config

**Comment by GustavoPrietoP** [comment]
> ![Screenshot from 2021-04-18 18-06-32](https://user-images.githubusercontent.com/70907734/115162320-d6797f00-a070-11eb-87f8-ec4305677bf3.png)
> im getting this error now. I have `local naughty = require('naighty')` on top of my noti-center.lua config

`local naughty = require('naughty')`  i mean*

**Comment by cinget** [comment]
In order for it to work for me, I had to install the latest version of awesomewm directly from the source code. After that, it started to work as it should. 

I was getting the same error message because I was lazy and chose to install it directly from my terminal, as @Mofiqul had specified, awesomewm has to be installed directly from the repository.

@GustavoPrietoP @Bad3r 

If you are interested in building from source code. I will be leaving the links for you to follow the instructions.

[Awesome Github Repository](https://github.com/awesomeWM/awesome/)
[List of dependencies](https://awesomewm.org/apidoc/documentation/10-building-and-testing.md.html)

After installing it, I was unable to see awesomewm on the xfce login screen. To solve this, I had to create an `awesome.desktop` file inside the `xsessions` folder (`usr/share/xsessions`)

Put the following code inside the `awesome.desktop` file:
```
[Desktop Entry]
Encoding=UTF-8
Name=awesome
Comment=Highly configurable framework window manager
TryExec=awesome
Type=Application
Exec=awesome
```

Then logout or restart your computer, and you should be ready to go.

**Comment by Bad3r** [comment]
@cinget @GustavoPrietoP 

Thank you! I was able to solve the issue by using the git version of the package i.e `awesome-git` from the aur

closed.
